import type { Metadata } from "next";
import localFont from "next/font/local";
import "../assets/styles/tailwind.css";

const inter = localFont({
  src: "../assets/fonts/Inter-VariableFont_opsz,wght.ttf",
  variable: "--font-inter",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} h-screen w-screen bg-neutral-50 antialiased`}>{children}</body>
    </html>
  );
}
