import { AppSidebar } from "@trustify/components/features/layouts/AppSidebar";
import { SidebarProvider } from "@trustify/components/ui/Sidebar";
import { Metadata } from "next";
import { PropsWithChildren } from "react";

export const metadata: Metadata = {
  title: "Dashboard",
  // description: "Generated by create next app",
};

export default function DashboardLayout({ children }: PropsWithChildren) {
  return (
    <SidebarProvider>
      <AppSidebar>{children}</AppSidebar>
    </SidebarProvider>
  );
}
